info:
  author: GIn
defaults:
  avatar: /images/avatar.jpg
colors:
  primary: "#8f7ff4"
  secondary: "#8587a7"
global:
  content_max_width: 1000px
  sidebar_width: 210px
  single_page: true
  open_graph:
    enable: true
    description: GIn's notebook
  website_counter:
    url: ""
    enable: false
    site_pv: false
    site_uv: false
    post_pv: false
home_banner:
  enable: true
  style: fixed
  title: GIn's notebook
  subtitle:
    text: [The world is my oyster.]
  social_links:
    enable: false
    links: []
    qrs: []
navbar:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
home:
  sidebar:
    enable: true
    position: left
    first_item: menu
articles:
  word_count:
    enable: true
    count: true
    min2read: true
  toc:
    enable: true
    max_depth: 3
  copyright: true
  lazyload: true
